name: "REFACTOR: 코드 개선"
description: 기능 변경 없이 내부 품질을 개선하는 Pull Request입니다.
title: "[REFACTOR] "
labels: ["refactor"]
body:
  - type: input
    id: summary
    attributes:
      label: 🔧 요약
      description: 어떤 부분을 리팩터링했는지 간단하게 설명해주세요
      placeholder: 예) UserService 중복 코드 제거 및 메서드 분리
    validations:
      required: true

  - type: input
    id: issue_link
    attributes:
      label: 🔗 관련 이슈
      description: 관련된 이슈 번호를 입력해주세요
      placeholder: 예) #123
    validations:
      required: false

  - type: textarea
    id: motivation
    attributes:
      label: 📌 리팩터링 배경
      description: 왜 이 리팩터링이 필요했는지 설명해주세요
      placeholder: |
        - 중복 코드로 인한 유지보수성 저하
        - 복잡한 메서드로 인한 가독성 문제
        - 테스트 어려운 구조
        - 성능 이슈
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: 🛠 주요 변경 사항
      description: 어떤 식으로 개선했는지 구체적으로 설명해주세요
      placeholder: |
        - 중복된 로직을 공통 유틸리티로 추출
        - 복잡한 메서드를 여러 개의 작은 메서드로 분리
        - Strategy 패턴 적용으로 조건문 개선
        - 의존성 주입으로 결합도 감소
    validations:
      required: true

  - type: checkboxes
    id: refactor_type
    attributes:
      label: 🔄 리팩터링 유형
      description: 적용한 리팩터링 기법을 체크해주세요
      options:
        - label: 메서드 추출/분리
        - label: 클래스 분리
        - label: 중복 코드 제거
        - label: 조건문 단순화
        - label: 매개변수 개선
        - label: 디자인 패턴 적용
        - label: 네이밍 개선
        - label: 패키지 구조 개선

  - type: textarea
    id: impact
    attributes:
      label: 📈 개선 효과
      description: 리팩터링으로 얻은 개선 효과를 설명해주세요
      placeholder: |
        - 코드 가독성 향상
        - 유지보수성 개선
        - 테스트 용이성 증가
        - 성능 개선 (구체적 수치 포함)
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: 📋 체크리스트
      description: PR 제출 전 확인사항
      options:
        - label: 기존 기능 동작 확인 완료
          required: true
        - label: 기존 테스트 모두 통과
          required: true
        - label: 코드 커버리지 유지/개선
        - label: 성능 저하 없음 확인
        - label: API 호환성 유지

  - type: textarea
    id: additional_info
    attributes:
      label: 📚 추가 정보
      description: 기타 참고사항이나 배경 정보
      placeholder: 추가적으로 전달하고 싶은 내용이 있다면 작성해주세요
    validations:
      required: false