services:
      fe:
        image: hojipkim/kimprun_fe:latest
        ports:
          - '3000:3000'
        env_file:
          - ENV_FILE_DIR
      redis:
        image: redis
        ports:
          - '6379:6379'
      scrap:
        image: hojipkim/kimprun_scrap:latest
        ports:
          - '8090:8090'
      db:
        image: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: kimprun
        ports:
          - '5432:5432'