name: "CHORE: 환경/설정/정리"
description: 기능 변경 없이 환경 설정, 정리, 삭제 등 내부 작업을 기록합니다.
title: "[CHORE] "
labels: ["chore"]
body:
  - type: textarea
    id: task
    attributes:
      label: 🔧 작업 내용
      description: 어떤 작업을 수행했는지 간결하게 설명해주세요.
      placeholder: |
        - 사용하지 않는 변수 제거
        - Dockerfile에 JDK 17 적용
        - GitHub Actions 캐시 경로 수정
        - Spring Boot 버전 2.7 → 3.1 업그레이드
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: 📂 작업 유형
      description: 어떤 종류의 작업인가요?
      options:
        - 의존성 업데이트
        - 설정/환경 변경
        - 불필요한 코드/파일 삭제
        - CI/CD 수정
        - 기타 메타 작업
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: 📌 영향 범위
      description: 개발/배포/CI 등에 미친 영향이 있다면 적어주세요.
      placeholder: |
        - 빌드 환경 변경으로 CI 실행 시간 단축 예상
        - 설정 변경으로 테스트가 실패할 수 있음
        - 사용되지 않는 설정 제거로 설정 파일 단순화
      validations:
        required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ 체크리스트
      options:
        - label: 로컬에서 변경 사항 확인 완료
        - label: CI/CD에서 정상적으로 동작 확인
        - label: 기능상 영향 없음 확인
        - label: 릴리즈 노트 작성 불필요
